### ISSUE TITLE
Add Nayuta and Ganesh

### ISSUE THREAD

**Issue by jdorigojones** [9cpluss/hardest-climbs#25]
Nayuta FA'd by Dai Koyamada and repeated by Yuta Imaizumi

Ganesh FA'd by Elias Iagnemma

**Comment by 9cpluss** [comment]
Hey, thanks a lot! Especially for the Japanese ones. It's not always easy finding out them.

**Comment by jdorigojones** [comment]
by the way, Gakido was downgraded to V15: https://www.youtube.com/watch?v=rN5Z3V4QYtA

**Comment by 9cpluss** [comment]
Thanks! That is odd. Did they change the title of the video? 8a.nu still has it logged as V16

**Comment by jdorigojones** [comment]
Yeah it was changed on the Mellow video (probably other discussions online somewhere too). Not sure which source you want to use, but it's possible they just haven't update 8a.nu

**Comment by 9cpluss** [comment]
Yeah, I think the Mellow video is a good enough source. Will remove it from the list.
