### ISSUE TITLE
Gakido 8C+?

### ISSUE THREAD

**Issue by Towbarli** [9cpluss/hardest-climbs#31]
It looks like you're missing this 8C+ : https://www.8a.nu/news/gakida-8c+-by-ryuichi-murai

It is also mentioned here: https://docs.google.com/document/d/1koaKcCSacMVIJepvk2kU6Iy-mBzHAqBT/edit

Although, here it is mentioned as a 8C, so difficult one haha: 
https://www.youtube.com/watch?v=rN5Z3V4QYtA

**Comment by 9cpluss** [comment]
Hey! Yeah, I actually had it on the list but then I came across the Mellow video which says 8C and that's why I removed it. But thank you anyway :)
