### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by bourbonspecial** [9cpluss/hardest-climbs#32]
It seems like https://www.hardestclimbs.com/ isn't responding. DNS seems to be resolving correctly. The server doesn't seem to be responding to requests?

**Comment by 9cpluss** [comment]
Thanks for letting me know! Yeah, something is up. Currently on holiday so hard to check what exactly is going on but it seems the hosting service is having issues. Will give it a few hours and check again.

**Comment by 9cpluss** [comment]
And right after writing this it started magically working again. Haha

**Comment by bourbonspecial** [comment]
Phew, glad it's sorted. Enjoy your hols.

**Comment by 9cpluss** [comment]
Thank you :)
